// ————————————————————————————————————————————————————————————————
// Mock data for the Cygnus console concept.
// Vocabulary is spec-faithful: apps run in cages (warm per-app servers),
// cold apps are revived, deploys are blue-green artifact swaps.
// ————————————————————————————————————————————————————————————————
// Tenant 0 is intentionally read-only until a typed daemon admin bridge exists.
export const tenant0 = Object.freeze({
  id: 'tenant-0',
  mode: 'preview',
  dataSource: 'fixture',
  dataSourceLabel: 'preview dataset',
  connection: 'offline',
  daemonBridge: 'offline',
  mutating: false,
});

export const node = {
  name: 'swan-01',
  domain: 'swan.host',
  kernel: 'Linux 6.8.0-45',
  kernelPatched: '3d ago',
  uptime: '41d 7h',
  ram: 32, // GB
  ramUsed: 7.3,
  ramCages: 5.9,
  ramEngines: 0.19,
  ramSystem: 1.21,
  warm: 41,
  registered: 287,
  binary: 'cygnus 0.9.2 · single binary · rustls · io_uring',
  engines: [
    { version: 'bun 1.2.19', def: true, text: '96 MB', apps: 251 },
    { version: 'bun 1.1.34', def: false, text: '92 MB', apps: 36 },
  ],
  coldStart: {
    p50: 34,
    p99: 92,
    phases: [
      { name: 'namespaces + cgroup', ms: 2.1 },
      { name: 'mounts + seccomp', ms: 1.2 },
      { name: 'exec engine + runtime init', ms: 24.6, hot: true },
      { name: 'bytecode load', ms: 5.3 },
      { name: 'shim binds UDS', ms: 0.8 },
    ],
  },
  certs: [
    { domain: '*.swan.host', kind: 'wildcard · DNS-01', renews: '61d', ok: true },
    { domain: 'atelier.studio', kind: 'custom · HTTP-01', renews: '34d', ok: true },
    { domain: 'helios.dev', kind: 'custom · HTTP-01', renews: '9d', ok: true },
  ],
  egress: {
    today: '18.4 GB',
    conns: '124k',
    modes: { public: 31, restricted: 5, none: 249, open: 2 },
    top: [
      { app: 'helios-api', gb: 9.1 },
      { app: 'atelier', gb: 4.2 },
      { app: 'ledger', gb: 2.8 },
      { app: 'prism-docs', gb: 1.1 },
    ],
  },
};

// identicon palettes — quiet duotones
const DUO = [
  ['#dfe5ff', '#2c46f0'],
  ['#d9f3e6', '#0da55f'],
  ['#efe6ff', '#7857f0'],
  ['#ffe9d6', '#e07c1f'],
  ['#dbeefc', '#1273b8'],
  ['#fde3e8', '#d5476b'],
  ['#e4f0d5', '#5c8f1d'],
  ['#e8e9ee', '#3d4351'],
];

export function identicon(name) {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0;
  const [bg, fg] = DUO[h % DUO.length];
  const angle = 30 + (h % 5) * 60;
  return { bg, fg, angle };
}

export const apps = [
  {
    id: 'atelier',
    name: 'atelier',
    domain: 'atelier.swan.host',
    custom: 'atelier.studio',
    framework: 'SvelteKit SSR',
    state: 'ready', // ready | cold | building | crashloop
    pinned: true, // min_instances: 1
    env: 'production',
    revival: 38,
    rss: 142,
    cpu: 4.2,
    conns: 12,
    cageUptime: '3h 12m',
    lastDeploy: '2m ago',
    branch: 'main',
    egress: 'public',
    memory: '256 MB',
    idleTtl: 'pinned warm',
    jit: true,
    engine: 'bun 1.2.19',
    envVars: 14,
    rps: 214,
    history: [1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1],
  },
  {
    id: 'helios-api',
    name: 'helios-api',
    domain: 'helios-api.swan.host',
    custom: 'helios.dev',
    framework: 'Express',
    state: 'ready',
    pinned: true,
    env: 'production',
    revival: 29,
    rss: 96,
    cpu: 11.8,
    conns: 84,
    cageUptime: '41d 7h',
    lastDeploy: '2d ago',
    branch: 'main',
    egress: 'public',
    memory: '512 MB',
    idleTtl: 'pinned warm',
    jit: true,
    engine: 'bun 1.2.19',
    envVars: 9,
    rps: 861,
    history: [1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 3, 1, 1, 1, 1, 1],
  },
  {
    id: 'ledger',
    name: 'ledger',
    domain: 'ledger.swan.host',
    custom: null,
    framework: 'Fastify + pg native',
    state: 'ready',
    pinned: false,
    env: 'production',
    revival: 44,
    rss: 188,
    cpu: 2.1,
    conns: 3,
    cageUptime: '26m',
    lastDeploy: '5h ago',
    branch: 'main',
    egress: 'restricted',
    memory: '256 MB',
    idleTtl: '10 min',
    jit: true,
    engine: 'bun 1.2.19',
    envVars: 11,
    rps: 32,
    history: [1, 2, 1, 1, 3, 1, 1, 1, 2, 1, 1, 3, 1, 1, 1, 1, 2, 1],
  },
  {
    id: 'prism-docs',
    name: 'prism-docs',
    domain: 'prism-docs.swan.host',
    custom: null,
    framework: 'Astro SSR',
    state: 'cold',
    pinned: false,
    env: 'production',
    revival: 41,
    rss: 0,
    cpu: 0,
    conns: 0,
    cageUptime: '—',
    lastDeploy: '1d ago',
    branch: 'main',
    egress: 'public',
    memory: '256 MB · small',
    idleTtl: '10 min',
    jit: false,
    engine: 'bun 1.2.19',
    envVars: 3,
    rps: 0,
    history: [1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'pulse-widget',
    name: 'pulse-widget',
    domain: 'pulse-widget.swan.host',
    custom: null,
    framework: 'Hono',
    state: 'building',
    pinned: false,
    env: 'production',
    revival: 31,
    rss: 54,
    cpu: 1.0,
    conns: 1,
    cageUptime: '2d 1h',
    lastDeploy: 'building now',
    branch: 'main',
    egress: 'none',
    memory: '128 MB · small',
    idleTtl: '10 min',
    jit: true,
    engine: 'bun 1.2.19',
    envVars: 2,
    rps: 118,
    history: [1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 4, 1, 1, 1],
  },
  {
    id: 'pr-412-checkout',
    name: 'pr-412-checkout',
    domain: 'pr-412-checkout.swan.host',
    custom: null,
    framework: 'SvelteKit SSR',
    state: 'cold',
    pinned: false,
    env: 'preview',
    revival: 41,
    rss: 0,
    cpu: 0,
    conns: 0,
    cageUptime: '—',
    lastDeploy: '3h ago',
    branch: 'feat/checkout-v2',
    egress: 'public',
    memory: '256 MB',
    idleTtl: '10 min',
    jit: true,
    engine: 'bun 1.2.19',
    envVars: 14,
    rps: 0,
    history: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1],
  },
  {
    id: 'pr-409-i18n',
    name: 'pr-409-i18n',
    domain: 'pr-409-i18n.swan.host',
    custom: null,
    framework: 'SvelteKit SSR',
    state: 'cold',
    pinned: false,
    env: 'preview',
    revival: 39,
    rss: 0,
    cpu: 0,
    conns: 0,
    cageUptime: '—',
    lastDeploy: '2d ago',
    branch: 'feat/i18n-routing',
    egress: 'public',
    memory: '256 MB',
    idleTtl: '10 min',
    jit: true,
    engine: 'bun 1.2.19',
    envVars: 14,
    rps: 0,
    history: [1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
  },
  {
    id: 'orbit-cron',
    name: 'orbit-cron',
    domain: 'orbit-cron.swan.host',
    custom: null,
    framework: 'Bun native',
    state: 'ready',
    pinned: false,
    env: 'production',
    revival: 26,
    rss: 38,
    cpu: 0.4,
    conns: 0,
    cageUptime: '12m',
    lastDeploy: '6d ago',
    branch: 'main',
    egress: 'restricted',
    memory: '128 MB · small',
    idleTtl: '30 min',
    jit: false,
    engine: 'bun 1.1.34',
    envVars: 6,
    rps: 2,
    history: [1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1],
  },
];

export const deploys = [
  {
    id: 'dpl_c81f2ae',
    app: 'pulse-widget',
    status: 'building',
    commit: 'tighten rate-limit window on /v1/beacon',
    branch: 'main',
    author: 'mika',
    when: 'now',
    dur: '—',
    size: '—',
    live: false,
  },
  {
    id: 'dpl_9f2c1a4',
    app: 'atelier',
    status: 'live',
    commit: 'checkout: prefetch payment intent on cart hover',
    branch: 'main',
    author: 'chase',
    when: '2m ago',
    dur: '9.4s',
    size: '1.24 MB',
    live: true,
  },
  {
    id: 'dpl_e33ab90',
    app: 'pr-412-checkout',
    status: 'preview',
    commit: 'wip: split shipping estimator into island',
    branch: 'feat/checkout-v2',
    author: 'mika',
    when: '3h ago',
    dur: '11.2s',
    size: '1.31 MB',
    live: false,
  },
  {
    id: 'dpl_b7d0c11',
    app: 'ledger',
    status: 'live',
    commit: 'pg: reuse prepared statements across pool',
    branch: 'main',
    author: 'chase',
    when: '5h ago',
    dur: '7.8s',
    size: '0.62 MB',
    live: true,
  },
  {
    id: 'dpl_a1e8f02',
    app: 'atelier',
    status: 'previous',
    commit: 'fix: hydration mismatch on locale switch',
    branch: 'main',
    author: 'ines',
    when: '1d ago',
    dur: '10.1s',
    size: '1.22 MB',
    live: false,
  },
  {
    id: 'dpl_77c9d3b',
    app: 'prism-docs',
    status: 'live',
    commit: 'docs: cage lifecycle diagrams',
    branch: 'main',
    author: 'ines',
    when: '1d ago',
    dur: '6.2s',
    size: '0.48 MB',
    live: true,
  },
  {
    id: 'dpl_5f4e21c',
    app: 'atelier',
    status: 'previous',
    commit: 'perf: inline critical css for product pages',
    branch: 'main',
    author: 'chase',
    when: '2d ago',
    dur: '9.9s',
    size: '1.21 MB',
    live: false,
  },
  {
    id: 'dpl_e90b774',
    app: 'pr-409-i18n',
    status: 'preview',
    commit: 'i18n: locale negotiation middleware',
    branch: 'feat/i18n-routing',
    author: 'ines',
    when: '2d ago',
    dur: '10.8s',
    size: '1.29 MB',
    live: false,
  },
  {
    id: 'dpl_2ac401d',
    app: 'helios-api',
    status: 'live',
    commit: 'v2: cursor pagination on /events',
    branch: 'main',
    author: 'mika',
    when: '2d ago',
    dur: '8.4s',
    size: '0.87 MB',
    live: true,
  },
  {
    id: 'dpl_91d3e5f',
    app: 'atelier',
    status: 'failed',
    commit: 'experiment: edge-side personalization',
    branch: 'main',
    author: 'ines',
    when: '3d ago',
    dur: '4.1s',
    size: '—',
    live: false,
  },
  {
    id: 'dpl_0c77b21',
    app: 'orbit-cron',
    status: 'live',
    commit: 'retry backoff for webhook fanout',
    branch: 'main',
    author: 'chase',
    when: '6d ago',
    dur: '5.9s',
    size: '0.31 MB',
    live: true,
  },
];

export const events = [
  { type: 'deploy', app: 'atelier', text: 'dpl_9f2c1a4 promoted · blue-green swap in 0.3s', when: '2m', tone: 'live' },
  { type: 'revival', app: 'pr-412-checkout', text: 'revived from cold in 41 ms', when: '9m', tone: 'cobalt' },
  { type: 'scale0', app: 'prism-docs', text: 'idle 10 min · cage reaped, artifact retained', when: '24m', tone: 'ghost' },
  { type: 'oom', app: 'ledger', text: 'exceeded 256 MB — cage restarted (2nd in 24h)', when: '1h', tone: 'amber' },
  { type: 'seccomp', app: 'orbit-cron', text: 'io_uring_setup blocked · filter held', when: '3h', tone: 'red' },
  { type: 'cert', app: '*.swan.host', text: 'wildcard renewed via DNS-01 · 90d', when: '1d', tone: 'ghost' },
  { type: 'deploy', app: 'helios-api', text: 'dpl_2ac401d promoted · previous retained', when: '2d', tone: 'live' },
];

// build log for the deploy detail screen
export const buildLog = [
  { t: '0.00', kind: 'head', text: 'cygnus deploy · atelier · main @ 41c9e2f' },
  { t: '0.02', kind: 'dim', text: 'uploading source · 812 KB · 214 files' },
  { t: '0.61', kind: 'ok', text: 'source received · sha256 9f2c…e11a' },
  { t: '0.63', kind: 'head', text: 'build cage · ephemeral overlay · egress allowlist: github.com, registry.npmjs.org' },
  { t: '0.71', kind: 'dim', text: 'lifecycle scripts: disabled (trustedDependencies)' },
  { t: '1.74', kind: 'text', text: 'bun install · 214 packages · lockfile verified' },
  { t: '5.52', kind: 'ok', text: 'install complete · 3.78s' },
  { t: '5.54', kind: 'text', text: 'bun build --bytecode · target bun 1.2.19' },
  { t: '7.91', kind: 'text', text: 'bundle.js   1.24 MB · 61 modules' },
  { t: '8.42', kind: 'text', text: 'bundle.jsc  3.41 MB · bytecode cache' },
  { t: '8.44', kind: 'ok', text: 'artifact sealed · content-addressed · ab9e02f1' },
  { t: '8.47', kind: 'head', text: 'blue-green swap' },
  { t: '8.51', kind: 'text', text: 'spawning cage · userns mntns pidns netns · seccomp v14' },
  { t: '8.89', kind: 'text', text: 'shim bound /cygnus/io/app.sock · readiness ok' },
  { t: '9.12', kind: 'text', text: 'route swapped atomically · draining previous cage' },
  { t: '9.40', kind: 'ok', text: 'live · https://atelier.swan.host · cold-start budget 38 ms' },
];

// latency series for Observe — [p50, p99] pairs, ms
export const latency = Array.from({ length: 48 }, (_, i) => {
  const wave = Math.sin(i / 5.2) * 6 + Math.sin(i / 2.3) * 3;
  const p50 = 24 + wave + (i % 7 === 3 ? 4 : 0);
  const p99 = 58 + wave * 2.4 + (i % 11 === 5 ? 26 : 0) + (i % 17 === 9 ? 14 : 0);
  return [Math.round(p50 * 10) / 10, Math.round(p99 * 10) / 10];
});

// request stream generator for Observe
const PATHS = [
  ['GET', '/api/products?cursor=61', 'atelier', 200],
  ['GET', '/', 'atelier', 200],
  ['POST', '/v1/events', 'helios-api', 202],
  ['GET', '/v1/events?cursor=9a2', 'helios-api', 200],
  ['GET', '/api/balance/acct_912', 'ledger', 200],
  ['POST', '/api/checkout/intent', 'atelier', 201],
  ['GET', '/docs/cages/lifecycle', 'prism-docs', 200],
  ['GET', '/v1/beacon', 'pulse-widget', 200],
  ['POST', '/v1/beacon', 'pulse-widget', 204],
  ['GET', '/healthz', 'helios-api', 200],
  ['GET', '/api/products/psi-lamp', 'atelier', 200],
  ['POST', '/api/transfers', 'ledger', 201],
  ['GET', '/assets/type-spec.css', 'prism-docs', 200],
  ['GET', '/api/search?q=oak', 'atelier', 200],
  ['DELETE', '/v1/events/e_88', 'helios-api', 204],
];

let reqSeq = 0;
export function nextRequest() {
  const p = PATHS[reqSeq++ % PATHS.length];
  const jitter = Math.random();
  const cold = jitter > 0.93;
  const dur = cold
    ? Math.round(38 + jitter * 40)
    : Math.round(3 + jitter * 26);
  const now = new Date();
  const hh = String(now.getHours()).padStart(2, '0');
  const mm = String(now.getMinutes()).padStart(2, '0');
  const ss = String(now.getSeconds()).padStart(2, '0');
  return {
    id: reqSeq,
    time: `${hh}:${mm}:${ss}`,
    method: p[0],
    path: p[1],
    app: p[2],
    status: jitter > 0.985 ? 500 : p[3],
    dur,
    cold,
  };
}

export const team = [
  { name: 'chase', role: 'owner', color: '#2c46f0' },
  { name: 'ines', role: 'deployer', color: '#0da55f' },
  { name: 'mika', role: 'deployer', color: '#7857f0' },
];

export const tokens = [
  { name: 'ci-github-actions', prefix: 'cyg_k1…9f2e', scope: 'deploy', last: '2m ago' },
  { name: 'agent-fleet', prefix: 'cyg_a7…03d1', scope: 'deploy · logs', last: '1h ago' },
];
